#!/bin/bash
# $1 - program to launch
# $2 - sbpl security policy file to use
# $3 - problem input file to send on stdin
# $4 - problem output file to redirect execution output into
# $5 - error file to capture any errors
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT=$(dirname "${DIR}")
sandbox-exec -D HERE="$PARENT" -f "$DIR/$2" $1 < "$3" > "$4" 2> "$5"

# see examples sandbox profiles in:
# /usr/share/sandbox/
# /System/Library/Sandbox/Profiles/
